/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f5f3ee",
        "tertiary-fixed-dim": "#d3c4b7",
        "on-secondary-fixed": "#241a00",
        "secondary-fixed": "#ffe088",
        "secondary-fixed-dim": "#e9c349",
        "primary-container": "#1c1b1b",
        "surface-container-highest": "#e4e2dd",
        "surface-container-lowest": "#ffffff",
        outline: "#747878",
        surface: "#fbf9f4",
        "on-surface-variant": "#444748",
        primary: "#000000",
        "surface-variant": "#e4e2dd",
        "on-primary": "#ffffff",
        "on-primary-container": "#858383",
        "on-secondary-container": "#745c00",
        secondary: "#735c00",
        "surface-container-high": "#eae8e3",
        "on-secondary": "#ffffff",
        "on-surface": "#1b1c19",
        error: "#ba1a1a",
        "on-background": "#1b1c19",
        background: "#fbf9f4",
        "outline-variant": "#c4c7c7",
        "on-primary-fixed": "#1c1b1b",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      spacing: {
        gutter: "24px",
        "stack-lg": "48px",
        "margin-mobile": "20px",
        "container-max": "1440px",
        "stack-xl": "80px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "margin-desktop": "64px",
        unit: "8px",
      },
      fontFamily: {
        "body-md": ["Montserrat"],
        caption: ["Montserrat"],
        "body-lg": ["Montserrat"],
        "label-md": ["Montserrat"],
        "headline-lg-mobile": ["Playfair Display"],
        "headline-md": ["Playfair Display"],
        "headline-lg": ["Playfair Display"],
        "display-lg-mobile": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};